apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-food-deployment
  labels:
    app: fast-food-deployment
spec:
  template:
    metadata:
      labels:
        app: fast-food-deployment
    spec:
      containers:
        - name: c-fast-food
          image: 528465521739.dkr.ecr.us-east-1.amazonaws.com/fast-food:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 1m
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secret-2
                  key: accessKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret-2
                  key: secretKey
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: aws-secret-2
                  key: sessionKey

  replicas: 1
  selector:
    matchLabels:
      app: fast-food-deployment