apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc-fast-food
  name: loadbalancer-svc-fast-food
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: fast-food-deployment
  type: LoadBalancer