name: Provide Infra Kubernetes

on:
  workflow_dispatch:

jobs:
  terraform:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Apply Terraform
        run: |
          cd terraform/
          terraform init
          terraform apply -auto-approve

      - name: Update Kubernetes
        run: |
          aws eks update-kubeconfig --name test-fiap --region us-east-1
          kubectl apply -f k8s/
